### ISSUE TITLE
Please allow usage of other network location providers

### ISSUE THREAD

**Issue by herrmanntom** [HelloVolla/android_vendor_volla#1]
This (and related) configuration options prevents installation of any NPL provider, except 'com.volla.nlp' package, which seemingly does not exist. Or at least its not shipped on the phone:
https://github.com/HelloVolla/android_vendor_volla/blob/618254b966cf349e5cdfec48cc4295ee3d3ff4a1/overlay/frameworks/base/core/res/res/values/config.xml#L40

For this reason there is not possibility to use one of these packages:
https://f-droid.org/en/packages/com.google.android.gms
https://f-droid.org/en/packages/org.microg.nlp

to then install some (privacy respecting offline) location provider backend of my choosing.

While I understand that the default google stuff gets removed, its not nice that there is now no option to use any provider at all.

**Comment by erfanoabdi** [comment]
you can install any custom backend,
Find volla nlp on settings -> apps -> show system apps -> unifiednlp -> advanced -> additional settings in the app

**Comment by herrmanntom** [comment]
I see. The unifiednlp is basically already bundled with the phone and a bit hidden.

The also bundled local GPS provider does not seem to work, even after updating the DB. But here is not the correct place to worry about this issues.
